- name: Install apache
  apt:
   update_cache: yes
   name: apache2
   state: present

- name: Copy HTML file to host
  copy:
   src: index.html
   dest: /var/www/html/index.html
   mode: '0644'

- name: start and enable apache
  service:
   name: apache2
   state: started
   enabled: yes

- name: Apache post install message
  debug:
    msg: "Apache has been installed and configured successfully"
